# Generated by Django 3.0.2 on 2020-02-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id_localidad', models.AutoField(db_column='ID_LOCALIDAD', primary_key=True, serialize=False)),
                ('nombre_localidad', models.CharField(db_column='NOMBRE_LOCALIDAD', max_length=15)),
            ],
            options={
                'db_table': 'LOCALIDAD',
                'managed': False,
            },
        ),
    ]
